changelog:
  exclude:
    labels:
      - skip-changelog
      - duplicate
    authors:
      - github-actions[bot]
  categories:
    - title: Breaking changes
      labels:
        - breaking
        - consensus
    - title: Node / Core
      labels:
        - node
        - core
    - title: Mining
      labels:
        - miner
        - mining
    - title: AI Compute
      labels:
        - compute
        - ai
    - title: Protocol
      labels:
        - protocol
    - title: Security
      labels:
        - security
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Other changes
      labels:
        - "*"
